exports.CHAT_ROOMS_LABELS = CHAT_ROOMS_LABELS = {
  LOBBY: {
    key: 'LOBBY',
    label: 'Lobby',
    value: 'lobby',
    room: '',
    visible: true,
    disabled: false,
    unreadMessages: 0,
    usersCount: 0,
  },
  EVENT: {
    key: 'EVENT',
    label: 'Event',
    value: 'event',
    room: '',
    visible: true,
    disabled: false,
    unreadMessages: 0,
    usersCount: 0,
  },
  POLLS: {
    key: 'POLLS',
    label: 'Polls',
    value: 'polls',
    room: '',
    visible: true,
    disabled: false,
    unreadMessages: 0,
    usersCount: 0,
  },
  WORKSHOP: {
    key: 'WORKSHOP',
    label: 'Workshop',
    value: 'workshop',
    room: '',
    visible: false,
    disabled: false,
    unreadMessages: 0,
    usersCount: 0,
  },
  CHANNEL: {
    key: 'CHANNEL',
    label: 'Channel',
    value: 'channel',
    room: '',
    visible: true,
    disabled: false,
    unreadMessages: 0,
    usersCount: 0,
  },
  PM: {
    key: 'PM',
    label: 'PM',
    value: 'pm',
    room: '',
    visible: false,
    disabled: false,
    unreadMessages: 0,
    usersCount: 0,
  },
}

exports.MAX_MESSAGES_IN_ROOM = MAX_MESSAGES_IN_ROOM = 300;
